In [7]:
import pandas as pd

df = pd.read_csv('clientes.csv', sep=';')

df.head()

   ID do Cliente,Nome Completo,Email,Telefone,Cidade
0  1001,Ana Silva,ana.silva@email.com,(21) 99876-...
1  1002,Bruno Oliveira,bruno.oliveira@email.com,(...
2  1003,Carla Santos,carla.santos@email.com,(31) ...
3  1004,Daniel Costa,daniel.costa@email.com,(41) ...
4  1005,Eduarda Pereira,eduarda.pereira@email.com...

In [8]:
import pandas as pd

pd.set_option('display.max_columns', None)      # Mostra todas as colunas
pd.set_option('display.max_colwidth', None)     # Não corta textos longos
pd.set_option('display.width', None)            # Ajusta à largura disponível

df = pd.read_csv('clientes.csv', sep=';')

df.head()

                             ID do Cliente,Nome Completo,Email,Telefone,Cidade
0            1001,Ana Silva,ana.silva@email.com,(21) 99876-1234,Rio de Janeiro
1       1002,Bruno Oliveira,bruno.oliveira@email.com,(11) 98765-4321,São Paulo
2      1003,Carla Santos,carla.santos@email.com,(31) 97654-3210,Belo Horizonte
3            1004,Daniel Costa,daniel.costa@email.com,(41) 96543-2109,Curitiba
4  1005,Eduarda Pereira,eduarda.pereira@email.com,(51) 95432-1098,Porto Alegre

                                                                                                                   0  \
ID do Cliente,Nome Completo,Email,Telefone,Cidade  1001,Ana Silva,ana.silva@email.com,(21) 99876-1234,Rio de Janeiro

                                                                                                                        1  \
ID do Cliente,Nome Completo,Email,Telefone,Cidade  1002,Bruno Oliveira,bruno.oliveira@email.com,(11) 98765-4321,São Paulo

                                                                                                                         2  \
ID do Cliente,Nome Completo,Email,Telefone,Cidade  1003,Carla Santos,carla.santos@email.com,(31) 97654-3210,Belo Horizonte

                                                                                                                   3  \
ID do Cliente,Nome Completo,Email,Telefone,Cidade  1004,Daniel Costa,daniel.costa@email.com,(41) 96543-2109,Curitiba

                                                                                                                             4
ID do Cliente,Nome Completo,Email,Telefone,Cidade  1005,Eduarda Pereira,eduarda.pereira@email.com,(51) 95432-1098,Porto Alegre